### ISSUE TITLE
Profile Page/Address Book

### ISSUE THREAD

**Issue by Will-WHyd** [Will-WHyd/Care_Compass_HealthPlanner#5]
## Statement
As a **user**, I can **view my profile page**, so that **I can view my consultant list and care team contact information**

# Acceptance Criteria
- Profile page is visible to user
- Profile page contains multiple fields of information, including Doctor list and Care Team list

## Tasks
- [ ]  Set up template 
- [ ]  Set up views for displaying profile page. Set up view to list doctors & contact info. Set up view for care team.
- [ ]  (optional) allow Care Team users to view profile page and see all information.
