### ISSUE TITLE
Adding Consultants

### ISSUE THREAD

**Issue by Will-WHyd** [Will-WHyd/Care_Compass_HealthPlanner#6]
## Statement
As a **user**, I can **add a doctor/care team member**, so that **gather a list of members of my care team and consultants and be able to quickly locate their contact information and share it**

# Acceptance Criteria
- User can add a doctor/care team member to their account via a form. Doctors can then be used to populate the 'doctor' field in appointments. 
- User can edit details or delete these entries
- (Optional) If the doctor/carer has an account, a user can add them to their account and connect them to their appointments
- (Optional) Patient user can update an existing entry with doctor user details, which will update those details on all appointments 

## Tasks
- [ ]  Set up models for doctors and for carers
- [ ]  Set up views to add and display on profile page
- [ ]  (Optional) logic to connect another user account and details to this entry.
